#!/bin/sh

# Wait for program coming up
wait_for_program () {
  n=0
  while true
  do
    # PID of last background command
    if xdotool search --onlyvisible --pid $! 2>/dev/null; then
      break
    else
      if [ $n -eq 90 ]; then
        notify-send -u critical "Error during start"
        break
      else
        n=`expr $n + 1`
        sleep 0.5
      fi
    fi
  done
}

## Merge Xresources
xrdb -merge ~/.Xresources &

## Desktop background or picture
#xsetroot -solid '#101010' &
feh --bg-scale "/home/lzap/Photos/Wallpapers/Brona-jaro09-1680.jpg" &

## Terminal daemon
#urxvt256cd -q -f -o &
TERMINAL=xterm

## Set startup volume (use pactl info to determine sink name)
pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo '60%' &

## Load "funny" sample
pactl upload-sample ~/.i3/that_was_easy.wav that_was_easy &
pactl upload-sample ~/.i3/volume_blip.wav volume_blip &

## Disable beeps
xset -b &

## Keybord layout setting
setxkbmap -layout cz,us -option grp:shift_shift_toggle &

## C-A-Backspace to kill X
#setxkbmap -option terminate:ctrl_alt_bksp &

## Turns on the numlock key in X11
#numlockx on &

## DPMS monitor setting (standby -> suspend -> off) (seconds)
xset dpms 600 1200 2000 &

## Set LCD brightness
xbacklight -set 100 &

## Gamma correction through the X server
#xgamma -gamma 1.1 &

## Composite manager
#xcompmgr -cf -r 0 -D 6 &

## Mouse and trackball setup
~/bin/configure-input-devices >/dev/null 2>&1 &

## Applets
LC_ALL=C parcellite &
LC_ALL=C nm-applet &

## OSD
dunst &

## Mail checker
~/work/gocheckmail/gocheckmail &

## apps with defined workspaces
sleep 1s
$TERMINAL -e weechat-curses &
#rednotebook &
#decibel-audio-player &
lexicon &
sleep 1s

VGA_YES=0
DP_YES=0
ANY_YES=0
xrandr | grep -q "DP2 connected" && DP_YES=1 && ANY_YES=1
xrandr | grep -q "VGA1 connected" && VGA_YES=1 && ANY_YES=1

## Workspaces 1-4
for w in 1 2 3 4; do
  i3-msg workspace $w
  $TERMINAL &
  wait_for_program
  if [ $DP_YES -eq 1 ]; then
    i3-msg split h
    $TERMINAL &
    wait_for_program
    i3-msg split v
    i3-msg "focus left; split v"
  else
    i3-msg layout tabbed
    $TERMINAL &
    wait_for_program
    i3-msg focus left
  fi
done

## Web and mail
i3-msg workspace 5
i3-msg split h
if [ $DP_YES -eq 1 ]; then
  $TERMINAL -name mail &
  wait_for_program
fi
google-chrome --auth-server-whitelist="*redhat.com" --proxy-pac-url=file:///home/lzap/proxies.pac &>/dev/null &
wait_for_program
if [ $DP_YES -eq 1 ]; then
  i3-msg resize grow width 10 px
fi
i3-msg "split v; layout stacking"

## Reconfigure - smaller VGA screen in office and huge DP at home
if [ $VGA_YES -eq 1 ]; then
  for w in 1 2 3 4 5; do
    i3-msg "workspace $w; move workspace to output VGA1"
  done
fi

## Refresh
xrefresh &

## Special keys
sleep 5s && xmodmap /home/lzap/.Xmodmap &

## Start Workrave
workrave &

## Good work :-)
exit 0
