#!/bin/bash
xrandr --output DP1 --off
xrandr --output DP2 --off
pacmd set-sink-port 0 analog-output-speaker
sleep 2
for W in $(seq 1 10); do
  i3-msg "workspace $W; move workspace to output LVDS1"
done
