#!/bin/bash
xrandr --output DP1 --off
i3-msg "workspace 1; move workspace to output right"
i3-msg "workspace 2; move workspace to output right"
i3-msg "workspace 3; move workspace to output right"
i3-msg "workspace 4; move workspace to output right"
