#!/bin/bash
killall mbsync 2>/dev/null
for DP in DP1 DP2 DP3; do
  xrandr --output $DP --off
  #xrandr --output VIRTUAL1 --off
done
pacmd set-sink-port 0 analog-output-speaker
sleep 2
nmcli r all on
for W in $(seq 1 10); do
  i3-msg "workspace $W; move workspace to output LVDS1"
done
